services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${ELASTICSEARCH_SERVICEACCOUNTTOKEN}
      - XPACK_GUIDEDONBOARDING_ENABLED=false
      - XPACK_SECURITY_ENCRYPTIONKEY=something_at_least_32_characters
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=something_different_at_least_32_chars
      - XPACK_REPORTING_ENCRYPTIONKEY=another_key_at_least_32_characters
      - XPACK_SECURITY_SECURECOOKIES=false
      - NODE_OPTIONS=--openssl-legacy-provider=0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: huynhnhatvuong1
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Cổng giao tiếp AMQP
      - "15672:15672" # Giao diện Web quản lý
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  elastic_data:
    driver: local
  redis_data:
    driver: local